/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "UPGRADE": "升级",
    "VERSION 1 (RELEASE)": "版本 1 (发布)",
    "YES": "是",
    "Welcome to your first universe\nA barren realm, the weakest among the infinite worlds scattered across existence\nThere is only one path forward: grow stronger, by any means necessary\nTrain, little warrior… and in time, the Multiverse itself will kneel before you": "欢迎来到你的第一个宇宙\nA贫瘠的世界，在分散存在的无限世界中最脆弱的世界\n前进的道路只有一条：用任何必要的手段变得更强大\n训练，小战士……假以时间，多元宇宙本身将向你屈膝",
    "Training": "训练",
    "TRAINING": "训练",
    "-Physical Training": "- 物理训练",
    "-Mental Training": "- 精神训练",
    "-Basic Challenger": "- 基础挑战者",
    "-Basic Hunting": "- 基础狩猎",
    "(Doesnt Reset Anything)": "（不会重置任何东西）",
    "ASCEND": "转生",
    "ASCENSION": "转生",
    "Ascension": "转生",
    "Attibutes": "属性",
    "Auto Ascend": "自动转生",
    "Auto Challenge Challenger": "自动挑战挑战者",
    "Autobuy Hunting Upgrades (Doesnt Consume Essence)": "自动购买狩猎升级（不消耗精华）",
    "Autobuy Hunts (Doesnt Consume Essence)": "自动购买狩猎（不消耗精华）",
    "Automation": "自动化",
    "CHALLENGE": "挑战",
    "Challenger": "挑战者",
    "Challengers, Creatures, just like you\nHere, strength is the only measure of worth, and the only way to prove it is to win\nA simple law of nature. No wealth, no luck, only raw Power\nBut if all that matters is to endlessly grasp for more Power…\nWhat meaning remains in the struggle itself?": "挑战者们，生物们，就像你们一样，在这里，力量是衡量价值的唯一标准，而证明它的唯一方法就是获胜。没有财富，没有运气，只有原始的力量，但如果所有重要的是无休止地攫取更多的权力，那么斗争本身还有什么意义呢？",
    "CHALLENGER": "挑战者",
    "CAUTION! ASCEND WILL RESET:": "小心！转生将重置:",
    "CRITICAL": "暴击",
    "DEFENCE": "防御",
    "DEFENCE PENETRATION": "防御穿透",
    "DO YOU WANT TO RESET THE SAVE?": "是否要重置存档？",
    "Energy": "能量",
    "Essence": "精华",
    "EVOLVE": "进化",
    "Export Save": "导出存档",
    "HUNTING": "狩猎",
    "Hunting": "狩猎",
    "HUNTING EVOLUTION": "狩猎进化",
    "Import Save": "导入存档",
    "LIFE REGENERATION": "生命值回复",
    "LIFE STEAL": "生命偷取",
    "MAX": "最大",
    "NO": "否",
    "MENTAL TRAINING": "精神训练",
    "PHYSICAL TRAINING": "物理训练",
    "Power": "力量",
    "SHIELD": "护盾",
    "RESET SAVE": "重置存档",
    "RESPEC": "洗点",
    "REWARDS": "奖励",
    "test": "测试",
    "There are two absolute truths in this world: you win, or you die\nBut what truly happens when something dies?\nSome claim its soul merges with yours, resonating in harmony\nOthers believe the fallen body grants its finest qualities\nAnd there are those who say it is simply the reward of killing\nA natural law written into existence itself\nNo one really knows the truth.\nThe only certainty is this: Essence flows from death, and Essence makes you stronger\nAnd that alone is enough to satisfy everyone": "在这个世界上有两个绝对的真理：你赢了，或者你死了。但是当一个东西死了之后到底发生了什么呢？\n有人声称它的灵魂与你的灵魂融合在一起，和谐地共鸣\n另一些人认为，堕落的身体赋予了它最好的品质\n还有人说，这只是杀戮的回报\n这是自然法则写入存在本身\n没有人真正知道真相。唯一确定的是：精华来自死亡，精华会让你更强大，仅此一点就足以让所有人满意",
    "Universal Challenger": "宇宙挑战者",
    "Universal Cores": "宇宙核心",
    "Universal Nodes": "宇宙节点",
    "Universal Shards": "宇宙碎片",
    "You Can Ascend Without Resetting, Permanently": "你可以在不重置的情况下转生，永久地",
    "You can spend Ascension Points in Energy": "你可以用转生点换取能量",
    "You stand at the pinnacle of this universe\nNothing can defeat you\nBut is that truly enough?\nAs you gaze at the endless stars, you glimpse a boundary, a limit only you can shatter\nBreaking this limit will tear you apart\nbut it is the only way to absorb the raw energy of a greater universe\nBeyond yours, there exist countless realms, some weaker, some far stronger.\nEach time you transcend your limits, you draw in the power of another universe, energies fundamental to its very existence\nWith every energy claimed, you evolve, becoming harder to challenge, harder to overthrow\nBut the question remains: how many universes lie beyond the veil?\nAnd if you never stop breaking your limits… will you one day stand at the pinnacle of all creation?": "你站在宇宙之巅，没有什么能打败你，但这就足够了吗？当你凝视着无尽的星空，你瞥见了一个界限，一个只有你才能打破的界限，打破这个界限会把你撕碎，但这是吸收更大宇宙原始能量的唯一方法，在你的世界之外，存在着无数的世界，有些更弱，有些更强。每当你超越自己的极限，你就会吸引另一个宇宙的力量，这是另一个宇宙存在的根本能量，随着每一次能量的消耗，你就会进化，变得更难挑战，更难推翻，但问题仍然存在：有多少宇宙在面纱之外？如果你不断突破自己的极限，你会不会有一天站在万物之巅？",
    "CHALLENGES": "挑战",
    "Each ascension you get an Ascension Point": "每次转生你都会得到一个转生点",
    "Breakthrough this universe limits, reach another universe,\n                                    Stronger Than The Last": "突破这个宇宙的极限，到达另一个宇宙，比上一个更强大",
    "As your abilities refine, you begin to strike a roadblock\nRaw strength can take you far, but not far enough. Talent must now emerge\nAttributes, when properly honed, reveal their true essence, a formula for growth\nYet to awaken them, you must gather fragments of other Universal Climbers like yourself\nSuch power demands sacrifice. Are you ready to face how much further you still have to climb?": "随着能力的提高，你开始遇到障碍。原始的力量可以带你走很远，但还不够远。天赋现在必须显现出来，经过适当的磨练，才能揭示其真正的本质，成长的公式，然而要唤醒它们，你必须收集像你一样的其他万能攀登者的碎片，这样的力量需要牺牲。你准备好面对你还有多少路要走了吗？",
    "(Only If Your Damage And Life Is Highter Than The Challenger's)": "（只有当你的伤害和生命比挑战者大的时候）",
    "Damage": "伤害",
    "Essence/s ×": "精华/秒 ×",
    "Insight": "洞察力",
    "Life": "生命值",
    "Physical Training ×": "物理训练 ×",
    "STOP": "停止",
    "TRAIN": "训练",
    "Push yourself beyond your limits, not only in flesh and bones strength resides": "把自己推到极限之外，力量不仅寓于骨肉之中",
    "Will": "意志",
    "Damage And Life Training ×": "伤害与生命训练 ×",
    "Demons have been meeting me, they tell me im the chosen": "恶魔见过我，他们说我是天选之子",
    "Disable Hunting": "禁用狩猎",
    "Draconic arts enchance my training... is the wyvern a dragon?": "龙语的艺术强化了我的训练...双足飞龙是龙吗？",
    "Essence/s": "精华/秒",
    "Fortunately no wyvern knights, i've already dealt with the knights alone": "幸好没有飞龙骑士，我已经独自对付过那些骑士了",
    "Only Training, harder Universal Challenger": "只有经过训练，才能成为更强大的宇宙挑战者",
    "People who failed this universe": "那些辜负了这个世界的人",
    "Slime": "史莱姆",
    "Slime cores when Ingested makes me stronger": "摄入史莱姆核心后，会变得更强",
    "Slime infused with blessings is an essence concentrator": "被祝福灌注的史莱姆是精华浓缩器",
    "The stronger i am, the stronger i spite death": "我越强壮，就越不怕死亡",
    "Total Life": "总生命",
    "Understanding zombies life forms makes me able inflict curses on my enemies! Am i evil?": "了解僵尸的生命形态使我能够对我的敌人施加诅咒！我邪恶吗？",
    "Why suddenly every knight wants to duel me? Werent Challengers enought?": "为什么突然间每个骑士都想和我决斗？挑战者还不够多吗？",
    "Will And Insight Training ×": "意志与洞察力训练 ×",
    "YOU": "你",
    "BUY MAX": "购买最大",
    "Challenger first reward ×": "挑战者首个奖励 ×",
    "Add": "增加",
    "Damage ×": "伤害 ×",
    "Demon": "恶魔",
    "Knight": "骑士",
    "Life ×": "生命值 ×",
    "of Damage to Life": "的伤害到生命值",
    "Wyvern": "双足飞龙",
    "You Are The Strongest In This Universe": "你已经是这个宇宙中最强大的存在",
    "Zombie": "僵尸",
    "Universal Challenger, Attributes, Automation": "宇宙挑战者, 属性, 自动化",
    "Universe": "宇宙",
    "×log(Knights)": "×log(骑士)",
    "×log(Power×LVL)": "×log(力量×等级)",
    "×log(U. Shards×LVL)": "×log(宇宙碎片×等级)",
    "×log(Total hunt levels per LVL)": "×log(总狩猎等级 每级)",
    "×LVL": "×等级",
    "(Requires adiacent upgrades)": "（需要相邻升级）",
    "Ascension Points": "转生点数",
    "Challenger Damage": "挑战者伤害",
    "Challenger Life": "挑战者生命",
    "Challenger Rewards": "挑战者奖励",
    "Damage & Life": "伤害 & 生命",
    "Damage Training": "伤害训练",
    "Each hunt grants a free matching upgrade:": "每次狩猎都会获得一个免费的匹配升级：",
    "Energy upgrades price": "能源升级价格",
    "Except fusion upgrades": "除了融合升级",
    "Hunts grant +": "狩猎奖励 +",
    "Life Training": "生命训练",
    "log(Universe Time)": "log(宇宙时间)",
    "log₁₀(Hunt)per LVL": "log₁₀(狩猎）每级",
    "per LVL": "每级",
    "times weaker per LVL": "时间变弱每级",
    "to Damage Training": "为伤害训练",
    "to Life Training": "为生命训练",
    "to previous hunt per LVL": "到之前的狩猎每级",
    "U. Nodes & Cores": "宇宙节点 & 核心",
    "Universal Challenger is": "宇宙挑战者是",
    "Wyverns Essence": "双足飞龙精华",
    "BET": "打赌",
    "ACTIVE": "活跃",
    "Attributes": "属性",
    "Critical Points": "暴击点数",
    "Damage and Life Training": "伤害与生命训练",
    "Damage and Life Training ×": "伤害和生命训练 ×",
    "Defence": "防御",
    "Defence Penetration Points": "防御穿透点数",
    "Defence Points": "防御点数",
    "Disable Universal Cores/s, Obtain Life Steal Equal To Universal Cores": "禁用宇宙核心/秒，获得与宇宙核心相同的生命偷取",
    "Essence ×": "精华 x",
    "EVOLUTION": "进化",
    "FILL": "填满",
    "Fill With Damage And Life Training": "充满伤害和生命训练",
    "Fill With Essence": "充满精华",
    "Fill With Universal Cores": "充满宇宙核心",
    "Life Steal Points": "生命偷取点数",
    "Life Steal:": "生命窃取:",
    "Odds ": "几率",
    "Penetration Points": "穿透点数",
    "Regeneration Points": "回复点数",
    "Shield Points": "护盾点数",
    "UNIVERSAL": "宇宙",
    "Universal Shards ×": "宇宙碎片 x",
    "UNLOCK ENERGY FUSION": "解锁能量融合",
    "Will and Insight Training ×": "意志与洞察力训练 ×",
    "LOAD": "加载",
    "Mountain": "高山",
    "Fire": "火",
    "SAVE": "保存",
    "Notation": "符号",
    "Sky": "天空",
    "Univ. Cores": "宇宙核心",
    "Univ. Nodes": "宇宙节点",
    "Univ. Shards": "宇宙碎片",
    "Universal Cores, forged from the hearts of your challengers, fuse and resonate, shattering unseen barriers\nA red rift tears open before you, emanating a heat you have never known\nPure, elemental fire\nThese flames cannot be touched, cannot be tamed. You can only feed them… and let them burn you anew\nElemental Universes, chaotic crucibles of creation and destruction, purer than any ordinary universe\nYou once reached for higher universes in the small pond you called ascension, but now a new paradigm unfolds before you\nThere is a raw, mysterious secret you have only glimpsed": "宇宙核心，从你的挑战者的心锻造，融合和共鸣，粉碎看不见的障碍，红色裂谷撕裂在你面前打开，散发出你从未知道的热量，纯净，元素之火，这些火焰无法触及，无法驯服。你只能喂养它们…然后让它们重新燃烧你\基本宇宙，混乱的创造和毁灭的坩埚，比任何普通的宇宙都纯净\n你曾经在你称为扬升的小池塘里到达更高的宇宙，但现在一个新的范例在你面前展开\n有一个原始的，神秘的秘密你只是瞥见了",
    "Buy upgrades to get points, points give bonuses": "购买升级以获得点数，点数会给予奖励",
    "Breakthrough this universe limits, reach another\n                                    universe,\n                                    Stronger Than The Last": "突破这个宇宙的极限，到达另一个宇宙，比上一个更强大",
    "Attributes dont directly effect any fight": "属性不会直接影响任何战斗",
    "Letters and Scientific": "字母和科学",
    "Maximum Universal Challenger": "最大宇宙挑战者",
    "Slime multiplies Essence ×": "史莱姆乘以精华 ×",
    "What is the universe?\nThe universe is made of energies, the more raw they are, and the more an universe contains them, the more likely for a better universe\nFlames ravage the very fabric of worlds, and in this chaos, you need water to cleanse and restore\nLooking back at your home, made of the simplest of energies, as big as a moon\nA question comes up, how can stronger universes sustain life?\nShouldn't Chaos consume them all?\nThe answer is Water, Water Universes, a new type of universe you just discovered, seems to be the coolant of this chaotic energies, making them able to coexist with each other\nIs it possible with Water to make my own universe possible to hold other energies?": "宇宙是什么？\n宇宙是由能量组成的，能量越原始，宇宙中包含的能量越多，宇宙就越有可能变得更好\n火焰会破坏世界的结构，在这种混乱中，你需要水来净化和恢复\n回头看看你的家，由最简单的能量组成，像月亮一样大\n问题来了，强大的宇宙如何维持生命？混沌不应该把他们全部吞噬吗？\n答案是水，水宇宙，你刚刚发现的一种新型宇宙，似乎是这种混乱能量的冷却剂，使它们能够彼此共存\水有没有可能使我自己的宇宙有可能容纳其他能量？",
    "1. Craft Potion": "1. 制作药剂",
    "1. Drag Equipped Potion and Drop it in the grid": "1. 拖动装备的药水并将其放入格子中",
    "2. Drag Potion and Drop it a slot": "2. 拖动药水并将其放入槽中",
    "3. Upgrade Potion": "3. 升级药水",
    "Accumulation": "积累",
    "Ambrosia": "特别美味的食物",
    "Ambrosia Max": "特别美味的食物上限",
    "ATTRIBUTES": "属性",
    "Beast King Arom": "兽王亚罗姆",
    "Beast Repellent": "驱兽剂",
    "Bottled Light": "瓶装光",
    "Core Tonic": "核心补药",
    "CRAFT": "工艺",
    "Critical and Life Regeneration Points": "致命点和生命回复点",
    "Defence Penetration and Defence points": "防守穿透和防守点",
    "DELETE": "删除",
    "Elixir": "长生不老药",
    "Elixir Max": "灵丹妙药马克斯",
    "Erbs": "雇员",
    "Extracted Gravity": "提取的重力",
    "Fey Touched": "垂死的感动",
    "Fire upgrades": "火升级",
    "Fluid Fire": "液体火灾",
    "FUSION": "融合",
    "Gu poison": "顾毒药",
    "Heat upgrades": "热升级",
    "How to Unequip:": "如何解除装备：",
    "Hunt upgrades Price": "狩猎升级价格",
    "Hunts Essence": "狩猎本质",
    "Hunts Price": "狩猎的价格",
    "Ingredients": "成分",
    "Insight Training": "洞察力训练",
    "Iron Will": "钢铁般的意志",
    "Life Steal and Shield points": "生命偷窃和护盾点数",
    "Liquid Death": "液体死亡",
    "Multiversal Warrior v1.3.0 - Elemental Update: Water Alchemist": "多元宇宙战士v1.3.0——元素更新:水炼金术士",
    "Nature's Embrace": "大自然的拥抱",
    "Place potions of the same type": "放置相同类型的药剂",
    "Place this potion in Source": "把这个药水放在源头",
    "Please Wait": "请稍等",
    "Potions": "药水",
    "Pyrofrost": "冰霜",
    "Size upgrades": "尺寸升级",
    "Source": "源",
    "SOURCE": "源",
    "Soured Ambrosia": "恶化特别美味的食物",
    "Stone Blessing": "石头的祝福",
    "times weaker": "弱倍",
    "Water": "水",
    "Water Gem": "水宝石",
    "Water Max": "水上限",
    "Water Upgrades": "水升级",
    "Will Training": "意志训练",
    "Wyvern Fury": "飞龙之怒",
    "In this reality, the mind sees more than eyes can, is this world enough??": "在这个现实中，心灵比眼睛能看到的更多，这个世界够吗？？",
    "Reset the level. Upgrade the effects.\xa0Raise\xa0the\xa0price": "重置等级。升级效果。提高价格",
    "Unlock New Training At 10 Power": "力量达到10解锁新训练",
    "Increase fight speed every 5s": "每5秒增加战斗速度",
    "Max Life": "最大生命值",
    "TANKS": "坦克",
    "Wind": "风",
    "Wind Affinity": "风亲和力",
    "Water Affinity": "水亲和力",
    "Earth Affinity": "地亲和力",
    "WARRIORS": "战士",
    "Training Grounds": "训练场",
    "SUPPORTS": "支持",
    "SOUL": "灵魂",
    "There is an old legend claiming that all beings were once shaped from earth itself.\nAs unbelievable as it may sound, there are creatures said to be born exactly this way.\nThe craft required to mold life from dirt,it is of such immense complexity that it borders on madness.\nYet a thought lingers in your mind: what if you attempted it regardless?\nWhat if you tried to forge something that reflects you, shaped by your own hands?\nA being of clay and intention... a Golem.": "有一个古老的传说，声称所有的生物都是由地球本身塑造的。虽然听起来难以置信，但据说有些生物就是这样出生的。从泥土中塑造生命所需要的技艺，它是如此的复杂以至于近乎疯狂。然而，一个想法在你脑海中萦绕：如果你不顾一切地尝试呢？如果你想用自己的双手打造一件能反映你自己的东西呢？\n是粘土和意图…一个傀儡。",
    "Metal": "金属",
    "Life × Golem Life (": "生命值 × 魔像生命值 (",
    "Life × Soul Life (": "生命值 × 灵魂生命值 (",
    "Damage × Soul Damage (": "伤害 × 灵魂伤害 (",
    "Damage × Golem Damage (": "伤害 × 魔像伤害 (",
    "Golems": "魔像",
    "Golem Army": "魔像军队",
    "Import From File": "从文件导入",
    "GLOBAL BONUS": "全局加成",
    "Earth": "地",
    "ARCHERS": "射手",
    "Affinity": "亲和力",
    "COMMANDER": "指挥官",
    "After this discovery, the Golems proved themselves capable of crossing the wind universe portal.\nThey ventured far and returned bearing treasures, won through battles\nagainst other golems.\nThese treasures appear to originate from foreign universes, or perhaps they are formed\nfrom raw, untamed energies themselves.\nWhen sculpted into rings or forged into blades, these energies gain a new strength,\nand some say they may even become vessels into the elemental universes.\nSouls.": "在这个发现之后，魔像证明了他们有能力穿越风宇宙之门。他们冒险远行，带着财宝回来，在与其他傀儡的战斗中获胜。这些宝藏似乎来自外星宇宙，或者它们本身就是由原始的、未驯服的能量形成的。当被雕刻成戒指或锻造成刀刃时，这些能量获得了新的力量，有人说它们甚至可以成为进入元素宇宙的容器。",
    "1. Make a strong army": "1. 组建一支强大的军队",
    "2. Drag Potion and Drop it in a slot": "2. 拖动药水并将其放入槽中",
    "2. Go in the WIND tab, and win expeditions": "2. 进入风的标签，并赢得探险",
    "3. CLAIM Treasures from expeditions, drag and drop them in the corresponding\n                                        slot": "3. 从探险中认领宝藏，将它们拖放到相应的插槽中",
    "3. CLAIM Treasures from expeditions, drag and drop them in the corresponding slot": "3. 从探险中获得宝藏，拖放到相应的槽中",
    "4. Upgrade the treasures in METAL": "4. 升级金属中的宝物",
    "Barracks": "军营",
    "Earth Spire": "大地塔尖",
    "Export To File": "导出到文件",
    "Fire Affinity": "火亲和力",
    "Formation": "阵型",
    "Formation: Default": "阵型：默认",
    "Mound": "土丘",
    "Multiversal Warrior v1.4.0 - Elemental Update: Golem Army": "多元宇宙战士v1.4.0 -元素更新：傀儡军队",
    "Steel Spire": "钢铁尖塔",
    "Training Grounds": "训练场地",
    "Iron": "铁",
    "Soul": "灵魂",
    "Silver": "银",
    "Pickaxe": "镐子",
    "Pyrite": "黄铁矿",
    "ORES": "矿石",
    "Multiversal Warrior v1.4.1 - Elemental Update: Mines": "多元宇宙战士 v1.4.1 - 元素更新: 矿山",
    "Miners": "矿工",
    "Mine Stats": "矿山统计",
    "Metal Foundation": "金属基础",
    "LOW FORGE": "低级锻炉",
    "LOW MINE": "低级矿山",
    "Amulets": "护身符",
    "Defeat Magma Elemental to unlock": "击败岩浆元素解锁",
    "Fused Stone": "融合石",
    "Hardness: Mine Power needed to damage ore": "硬度：破坏矿石所需的矿山力量",
    "Life: Mine Power / Life equals ore": "生命：矿山力量 / 生命等于矿石",
    "Life: Mine Power / Life equals ore/秒": "生命：矿山力量 / 生命等于矿石/秒",
    "LOW\n                                        FORGE": "低级\n                                         锻炉",
    "LOW\n                                        MINE": "低级\n                                         矿山",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Multiversal Warrior v1.1.0 - Elemental Update: Fire Rift": "多元宇宙战士v1.1.0 -元素更新：火焰裂谷",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Universal Shards: ": "宇宙碎片: ",
    "Maximum Active Trainings: ": "最大同时训练上限: ",
    "Ascension Requires Challenger ": "转生要求 挑战者 ",
    "Bet": "打赌",
    "Tier ": "层级 ",
    "Reach Burnt Universe ": "到达燃烧宇宙 ",
    "Earth/s × completed Expeditions ": "地球/秒×远征完成次数 ",
    "Metal/s + completed Crusades ": "金属/秒 + 完成十字军 ",
    "Divide Golems between every Golem Type ": "在每个傀儡类型之间划分傀儡 ",
    "Earth ×": "地 ×",
    "Golem damage ×": "魔像伤害 ×",
    "Golem life ×": "魔像生命值 ×",
    "Miners +": "矿工 +",
    "Mine Power ×": "矿山之力 ×",
    "Metal ×": "金属 ×",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/s": "/秒",
    "Universal Nodes To Level Up Defence": "宇宙节点以提升防御能力",
    " fight speed": " 战斗速度",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\-([\d\.]+)e([\d\.,]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)\)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^\(\+([\d\.]+)\)$/,
    /^\(\-([\d\.]+)\)$/,
    /^\(×([\d\.]+)\)$/,
    /^\(([\d\.]+)k\)$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^\/([\d\.]+)$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Reach (.+) Damage to unlock Knight (.+)$/, '达到 $1 伤害以解锁 骑士 $2'],
    [/^Reach (.+) Damage to unlock Demon (.+)$/, '达到 $1 伤害以解锁 恶魔 $2'],
    [/^Reach (.+) Damage to unlock Zombie (.+)$/, '达到 $1 伤害以解锁 僵尸 $2'],
    [/^Reach (.+) Damage to unlock Wyvern (.+)$/, '达到 $1 伤害以解锁 双足飞龙 $2'],
    [/^Reach (.+) Damage to unlock Slime (.+)$/, '达到 $1 伤害以解锁 史莱姆 $2'],
    [/^Reach (.+) Demon (.+)$/, '达到 $1 恶魔 $2'],
    [/^Reach (.+) Knight (.+)$/, '达到 $1 骑士 $2'],
    [/^Reach (.+) Slime (.+)$/, '达到 $1 史莱姆 $2'],
    [/^Reach (.+) Wyvern (.+)$/, '达到 $1 双足飞龙 $2'],
    [/^Reach (.+) Zombie (.+)$/, '达到 $1 僵尸 $2'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/([\d\.]+) Ascension Points$/, '$1\/$2 转生点数'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) Life Steal Points$/, '$1 生命偷取点数'],
    [/^([\d\.]+) Defence Points$/, '$1 防御点数'],
    [/^([\d\.]+) Critical Points$/, '$1 暴击点数'],
    [/^([\d\.]+) Regeneration Points$/, '$1 回复点数'],
    [/^([\d\.]+) Defence Penetration Points$/, '$1 防御穿透点数'],
    [/^([\d\.]+) Critical damage:$/, '$1 暴击伤害:'],
    [/^([\d\.]+) Critical rate:$/, '$1 暴击率:'],
    [/^([\d\.]+) Maximum life regeneration:$/, '$1 最大生命回复:'],
    [/^([\d\.]+) Maximum life steal:$/, '$1 最大生命偷取:'],
    [/^([\d\.]+) Maximum shield:$/, '$1 最大护盾:'],
    [/^([\d\.]+) Maximum defence:$/, '$1 最大防御:'],
    [/^([\d\.]+) Maximum defence penetration:$/, '$1 最大防御穿透:'],
    [/^([\d\.]+) Mine Power$/, '$1 矿山之力'],
    [/^([\d\.]+) Hardness$/, '$1 硬度'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) Defence$/, '$1 防御'],
    [/^([\d\.]+) Life Steal$/, '$1 生命偷取'],
    [/^([\d\.]+) Shield Points$/, '$1 护盾点塑'],
    [/^×([\d\.]+) per LVL$/, '×$1 每级'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Damage$/, '$1 伤害'],
    [/^([\d\.,]+) Tanks$/, '$1 坦克'],
    [/^([\d\.,]+) Weight$/, '$1 重量'],
    [/^([\d\.,]+) Supports$/, '$1 支持'],
    [/^([\d\.,]+) Life$/, '$1 生命值'],
    [/^([\d\.,]+) Commanders$/, '$1 指挥官'],
    [/^([\d\.,]+) Archers$/, '$1 射手'],
    [/^([\d\.,]+) Warriors$/, '$1 战士'],
    [/^([\d\.,]+) Miners$/, '$1 矿工'],
    [/^Unlock new training at ([\d\.,]+) Power$/, '解锁新的训练在 $1 力量'],
    [/^Reach ([\d\.,]+) Life$/, '达到 $1 生命值'],
    [/^Universal Challenger ([\d\.,]+)$/, '宇宙挑战者 $1'],
    [/^Defeat Challenger ([\d\.,]+)$/, '击败挑战者 $1'],
    [/^Reach Universe ([\d\.,]+)$/, '达到宇宙 $1'],
    [/^Challenger ([\d\.,]+)$/, '挑战者 $1'],
    [/^BUY ([\d\.,]+)$/, '购买 $1'],
    [/^Ascend To Universe ([\d\.,]+)$/, '转生到宇宙 $1'],
    [/^Universe ([\d\.,]+)$/, '宇宙 $1'],
    [/^Life \+([\d\.,]+) \(([\d\.,]+)\)$/, '生命值 +$1 ($2)'],
    [/^Damage \+([\d\.,]+) \(([\d\.,]+)\)$/, '伤害 +$1 ($2)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Slime \(([\d\.,]+)\)$/, '史莱姆 ($1)'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);